prometheus:
  prometheusSpec:
    retention: 15d
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 800Mi
        cpu: 500m

grafana:
  enabled: true
  adminPassword: "prometheus123"
  service:
    type: LoadBalancer
  resources:
    requests:
      memory: 200Mi
      cpu: 100m

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true